# PostgreSQL Database Configuration
spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/titantrade
    username : ${DB_USERNAME}
    password : ${DB_PASSWORD}
    driver-class-name : org.postgresql.Driver

# Hibernate Configuration

  jpa:
    database-platform : org.hibernate.dialect.PostgreSQLDialect
    hibernate :
      ddl-auto : validate
    show-sql : false
    
app:
  jwt:
    secret : ${JWT_SECRET}
    expiration-time-ms : ${EXPIRATION_TIME_MS:3600000}